using Microsoft.Extensions.Logging;
using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Plugins.Records;

using Apocrypha.Abstractions.Loadouts;
using Apocrypha.Abstractions.Loadouts.Synchronizers;
using Apocrypha.Abstractions.Loadouts.Synchronizers.Rules;
using Apocrypha.Games.CreationEngine.Abstractions;
using Apocrypha.Games.CreationEngine.SortOrder;
using NexusMods.Hashing.xxHash3;
using NexusMods.MnemonicDB.Abstractions;
using NexusMods.Paths;
using OneOf;
using Apocrypha.Sdk.FileStore;
using Apocrypha.Sdk.Games;
using Apocrypha.Sdk.Loadouts;

namespace Apocrypha.Games.CreationEngine;

public class PluginsFile : IIntrinsicFile
{
    private readonly ICreationEngineGame _game;
    private readonly PluginSortOrderVariety _sortOrderVariety;
    private readonly ILogger<PluginsFile> _logger;

    private record struct Metadata(RelativePath FileName, ModKey ModKey, Hash Hash, IMod Mod);

    public PluginsFile(ILogger<PluginsFile> logger, ICreationEngineGame game, PluginSortOrderVariety sortOrderVariety)
    {
        _game = game;
        _sortOrderVariety = sortOrderVariety;
        Path = game.PluginsFile;
        _logger = logger;
    }

    public GamePath Path { get; }

    public async Task Write(Stream stream, Loadout.ReadOnly loadout, Dictionary<GamePath, SyncNode> syncTree)
    {
        var plugins = await syncTree
            .Where(p => p.Key.Parent == KnownPaths.Data && KnownCEExtensions.PluginFiles.Contains(p.Key.Extension))
            .Where(p => p.Value.HaveLoadout)
            .ToAsyncEnumerable()
            .SelectAwait(MakeMetadata)
            .Where(static metadata => metadata.HasValue)
            .Select(static metadata => metadata!.Value)
            .ToDictionaryAsync(x => x.ModKey);

        if (plugins.Count == 0)
            return;

        // The persisted sort order is the preference layer: curated by a collection, arranged in
        // the load-order UI, or absent entirely. Master references are re-applied as hard
        // constraints below — they are correctness, not preference — so the file can never order a
        // plugin ahead of one it requires, no matter what the persisted order says. Plugins the
        // persisted order does not mention fall back to the conventional (masters, light, regular)
        // block order that every mainstream tool emits, with a name tie-break so an unchanged
        // load-out produces an identical plugins.txt on every apply.
        var persistedOrder = _sortOrderVariety.GetPersistedPluginOrder(loadout.LoadoutId, loadout.Db);
        Dictionary<string, int>? curatedIndex = null;
        if (persistedOrder.Count > 0)
        {
            curatedIndex = new Dictionary<string, int>(persistedOrder.Count, StringComparer.OrdinalIgnoreCase);
            for (var i = 0; i < persistedOrder.Count; i++)
            {
                curatedIndex.TryAdd(persistedOrder[i], i);
            }
        }

        var pluginList = plugins.Values.ToList();
        var nodes = pluginList
            .Select(p => new LoadOrderSorting.PluginNode(
                p.FileName.ToString(),
                p.Mod.MasterReferences.Select(m => m.Master.FileName.ToString()).ToArray()
            ))
            .ToList();

        var order = LoadOrderSorting.SortPlugins(nodes, curatedIndex, out var cyclePlugins);
        if (cyclePlugins.Count > 0)
        {
            // Only malformed plugin headers can close a master loop; the affected plugins are
            // still written, in preference order, after everything sortable.
            _logger.LogWarning("Master references form a cycle involving {Plugins}; their relative order falls back to preference",
                string.Join(", ", cyclePlugins.Take(5)));
        }

        _logger.LogDebug("Sorted {Count} plugin files ({Persisted} with a persisted position)", pluginList.Count, curatedIndex?.Count ?? 0);

        await using var sw = new StreamWriter(stream, leaveOpen: true);
        await sw.WriteLineAsync("# Generated by Apocrypha");

        foreach (var index in order)
        {
            await sw.WriteLineAsync($"*{pluginList[index].FileName}");
        }

        await sw.FlushAsync();
    }

    private async ValueTask<Metadata?> MakeMetadata(KeyValuePair<GamePath, SyncNode> arg)
    {
        var relPath = arg.Key.Path.FileName;
        Hash hash;

        // We need to figure out if we should look at the loadout or the disk
        var syncNode = arg.Value;
        if (syncNode.Actions.HasFlag(Actions.ExtractToDisk) || syncNode.Disk.Hash == Hash.Zero || syncNode.SourceItemType == LoadoutSourceItemType.Game)
            hash = syncNode.Loadout.Hash;
        else
            hash = syncNode.Disk.Hash;

        IMod? modHeader;
        try
        {
            modHeader = await _game.ParsePlugin(hash, relPath);
        }
        catch (Exception e)
        {
            // One corrupt plugin must degrade to one missing plugins.txt line, not abort the
            // whole write -- that fails every Apply until the user hunts down the bad file.
            _logger.LogWarning(e, "Failed to parse the header of plugin `{Plugin}`; leaving it out of the plugins file", relPath);
            return null;
        }

        if (modHeader == null)
        {
            _logger.LogWarning("No readable content for plugin `{Plugin}` (unknown hash?); leaving it out of the plugins file", relPath);
            return null;
        }

        return new Metadata(relPath, modHeader.ModKey, hash, modHeader);
    }


    /// <summary>
    /// Learns the order from a plugins.txt this app did not write — either hand-edited, or already
    /// present before the game was managed — by persisting it as the loadout's plugin order.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Reaching this method means the file on disk differs from what we last recorded, which the
    /// action mapping routes to <c>AdaptLoadout</c> rather than <c>WriteIntrinsic</c>. While this was
    /// a no-op that had a compounding cost: the edit was never learned, and because the same
    /// signature does not carry <c>WriteIntrinsic</c>, the file was not regenerated either — so an
    /// edited plugins.txt stayed frozen and no persisted order, curated or hand-arranged, could ever
    /// reach disk. Review finding B-1.
    /// </para>
    /// <para>
    /// Only the <b>order</b> is learned. The <c>*</c> prefix marks a plugin as enabled, but mod
    /// enablement lives on loadout items and is not this file's to decide, so a disabled entry
    /// contributes its position and nothing else. Order is also a preference, not a guarantee:
    /// <see cref="Write"/> re-applies master references as hard constraints, so an ingested order
    /// that puts a plugin ahead of its master comes back corrected rather than being honoured.
    /// </para>
    /// <para>
    /// The transaction is deliberately unused. Persisting a sort order goes through
    /// <c>ApplyCuratedOrder</c>, which owns a compare-and-swap retry loop and commits for itself; the
    /// alternative was a transaction-participating variant of that machinery, which is a rework of
    /// the CAS path for no behavioural gain here. The consequence is that a failure after this point
    /// in the sync leaves the learned order committed while the rest of the sync rolls back — the
    /// order is a preference and re-learning it is idempotent, so that is the harmless direction to
    /// fail in.
    /// </para>
    /// </remarks>
    public async Task Ingest(Stream stream, Loadout.ReadOnly loadout, Dictionary<GamePath, SyncNode> syncTree, ITransaction tx)
    {
        var order = await ParseOrder(stream);
        if (order.Count == 0)
        {
            _logger.LogDebug("`{Path}` listed no recognisable plugins; leaving the persisted order alone", Path);
            return;
        }

        _logger.LogInformation("Learning the plugin order from `{Path}` ({Count} plugin(s))", Path, order.Count);

        await _sortOrderVariety.ApplyCuratedOrder(
            loadout.LoadoutId,
            OneOf<LoadoutId, CollectionGroupId>.FromT0(loadout.LoadoutId),
            order
        );
    }

    /// <summary>
    /// Reads plugin file names from a plugins.txt in file order, preserving the casing on disk.
    /// </summary>
    internal static async Task<List<string>> ParseOrder(Stream stream)
    {
        var order = new List<string>();
        var seen = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        using var reader = new StreamReader(stream, leaveOpen: true);
        while (await reader.ReadLineAsync() is { } line)
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0) continue;
            if (trimmed.StartsWith('#')) continue;

            // A leading '*' means enabled. We take the position either way; see Ingest's remarks.
            if (trimmed.StartsWith('*')) trimmed = trimmed[1..].Trim();
            if (trimmed.Length == 0) continue;

            // Ignore anything that is not a plugin: these files are hand-edited, and a stray word
            // must not become a phantom entry in the persisted order.
            var extension = RelativePath.FromUnsanitizedInput(trimmed).Extension;
            if (!KnownCEExtensions.PluginFiles.Contains(extension)) continue;

            // Duplicates are ignored case-insensitively, but the casing kept is the first one seen:
            // persisted plugin names are a display-casing contract elsewhere in the engine.
            if (!seen.Add(trimmed)) continue;
            order.Add(trimmed);
        }

        return order;
    }
}
