#!/usr/bin/env python3
"""Generate bepinex-nexus-ids.json: settingsIdentifier -> Nexus game id.

Joins the Thunderstore ecosystem schema's BepInEx games against the vendored
games.json (Nexus domains) by normalized display name. Exact-unique matches only:
if either side has two entries normalizing to the same key, no mapping is emitted
for that key. Hand-verified expectations for the design-doc verification set are
asserted at the end. Run from the repo root.
"""
import json
import re
import sys

SCHEMA = "src/Apocrypha.Games.BepInEx/Assets/ecosystem-schema.json"
GAMES_JSON = "src/Apocrypha.Networking.NexusWebApi/Assets/games.json"
OUT = "src/Apocrypha.Games.BepInEx/Assets/bepinex-nexus-ids.json"


def norm(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "", name.lower())


schema = json.load(open(SCHEMA))
nexus = json.load(open(GAMES_JSON))

# Nexus side: normalized name -> list of (id, name, domain)
nexus_by_name = {}
for entry in nexus:
    nexus_by_name.setdefault(norm(entry["name"]), []).append(entry)

# Schema side: the same filter the C# parser uses (bepinex client instances w/ steam id)
candidates = []  # (settingsIdentifier, displayName)
for slug, game in schema["games"].items():
    for inst in game.get("r2modman") or []:
        if inst["gameInstanceType"] != "game":
            continue
        if inst["packageLoader"] != "bepinex":
            continue
        steam = [d for d in inst["distributions"] if d["platform"] == "steam" and d.get("identifier")]
        if not steam:
            continue
        candidates.append((inst["settingsIdentifier"], inst["meta"]["displayName"]))

# Schema-side normalized-name collisions are ambiguous too
schema_by_name = {}
for sid, name in candidates:
    schema_by_name.setdefault(norm(name), []).append(sid)

mappings = {}
unmatched = []
ambiguous = []
for sid, name in candidates:
    key = norm(name)
    if len(schema_by_name[key]) > 1:
        ambiguous.append(f"{sid} (schema-side name collision: {name})")
        continue
    hits = nexus_by_name.get(key, [])
    if len(hits) == 1:
        mappings[sid] = hits[0]["id"]
    elif len(hits) > 1:
        ambiguous.append(f"{sid} (nexus-side name collision: {name} -> {[h['domain_name'] for h in hits]})")
    else:
        unmatched.append(sid)

# Values must be unique (two schema games must not claim one Nexus id — locator dicts throw)
seen = {}
for sid, nid in list(mappings.items()):
    if nid in seen:
        ambiguous.append(f"{sid} + {seen[nid]} both mapped to Nexus id {nid}; dropping both")
        del mappings[sid]
        del mappings[seen[nid]]
    else:
        seen[nid] = sid

# Hand-verified verification set (design doc §3); RiskOfRain2/H3VR are Nexus-less on purpose
expected = {
    "Subnautica": 1155, "SubnauticaBZ": 2706, "LethalCompany": 5848, "Valheim": 3667,
    "ContentWarning": 6301, "REPO": 7398, "PEAK": 7867, "GTFO": 3657,
    "ULTRAKILL": 3515, "Timberborn": 4074,
}
errors = [f"{sid}: expected {nid}, got {mappings.get(sid)}" for sid, nid in expected.items() if mappings.get(sid) != nid]
if errors:
    sys.exit("VERIFICATION SET MISMATCH:\n" + "\n".join(errors))
for nexus_less in ("RiskOfRain2", "H3VR"):
    if nexus_less in mappings:
        sys.exit(f"{nexus_less} unexpectedly matched a Nexus id: {mappings[nexus_less]}")

out = {
    "$comment": "Generated by name-matching the ecosystem schema against the vendored games.json "
                "(exact-unique normalized-name matches only; verification set hand-confirmed — see "
                "DESIGN-bepinex-family.md §4b). Regenerate when re-vendoring either input.",
    "mappings": dict(sorted(mappings.items())),
    "unmatched": sorted(unmatched),
    "ambiguous": sorted(ambiguous),
}
json.dump(out, open(OUT, "w"), indent=2)
print(f"candidates={len(candidates)} mapped={len(mappings)} unmatched={len(unmatched)} ambiguous={len(ambiguous)}")
print("AMBIGUOUS:", *ambiguous, sep="\n  ")
